//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundExplorers.View.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoundExplorers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ActionsDocumentNew16x16 {
            get {
                object obj = ResourceManager.GetObject("ActionsDocumentNew16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsDocumentNew32x32 {
            get {
                object obj = ResourceManager.GetObject("ActionsDocumentNew32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsDocumentNew48x48 {
            get {
                object obj = ResourceManager.GetObject("ActionsDocumentNew48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsDocumentOpen16x16 {
            get {
                object obj = ResourceManager.GetObject("ActionsDocumentOpen16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsDocumentOpen32x32 {
            get {
                object obj = ResourceManager.GetObject("ActionsDocumentOpen32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsDocumentOpen48x48 {
            get {
                object obj = ResourceManager.GetObject("ActionsDocumentOpen48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsEditCopy16x16 {
            get {
                object obj = ResourceManager.GetObject("ActionsEditCopy16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsEditCopy32x32 {
            get {
                object obj = ResourceManager.GetObject("ActionsEditCopy32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsEditCopy48x48 {
            get {
                object obj = ResourceManager.GetObject("ActionsEditCopy48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsEditCut16x16 {
            get {
                object obj = ResourceManager.GetObject("ActionsEditCut16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsEditCut32x32 {
            get {
                object obj = ResourceManager.GetObject("ActionsEditCut32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsEditCut48x48 {
            get {
                object obj = ResourceManager.GetObject("ActionsEditCut48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsEditPaste16x16 {
            get {
                object obj = ResourceManager.GetObject("ActionsEditPaste16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsEditPaste32x32 {
            get {
                object obj = ResourceManager.GetObject("ActionsEditPaste32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsEditPaste48x48 {
            get {
                object obj = ResourceManager.GetObject("ActionsEditPaste48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsViewRefresh16x16 {
            get {
                object obj = ResourceManager.GetObject("ActionsViewRefresh16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsViewRefresh32x32 {
            get {
                object obj = ResourceManager.GetObject("ActionsViewRefresh32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActionsViewRefresh48x48 {
            get {
                object obj = ResourceManager.GetObject("ActionsViewRefresh48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CopyImage {
            get {
                object obj = ResourceManager.GetObject("CopyImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CutImage {
            get {
                object obj = ResourceManager.GetObject("CutImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevicesVideoDisplay16x16 {
            get {
                object obj = ResourceManager.GetObject("DevicesVideoDisplay16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevicesVideoDisplay32x32 {
            get {
                object obj = ResourceManager.GetObject("DevicesVideoDisplay32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevicesVideoDisplay48x48 {
            get {
                object obj = ResourceManager.GetObject("DevicesVideoDisplay48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FredFlintstone {
            get {
                object obj = ResourceManager.GetObject("FredFlintstone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpAndSupport16x16 {
            get {
                object obj = ResourceManager.GetObject("HelpAndSupport16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpAndSupport32x32 {
            get {
                object obj = ResourceManager.GetObject("HelpAndSupport32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpAndSupport48x48 {
            get {
                object obj = ResourceManager.GetObject("HelpAndSupport48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpImage {
            get {
                object obj = ResourceManager.GetObject("HelpImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MusicLibrary16x16 {
            get {
                object obj = ResourceManager.GetObject("MusicLibrary16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MusicLibrary32x32 {
            get {
                object obj = ResourceManager.GetObject("MusicLibrary32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MusicLibrary48x48 {
            get {
                object obj = ResourceManager.GetObject("MusicLibrary48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewImage {
            get {
                object obj = ResourceManager.GetObject("NewImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap News16x16 {
            get {
                object obj = ResourceManager.GetObject("News16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap News32x32 {
            get {
                object obj = ResourceManager.GetObject("News32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap News48x48 {
            get {
                object obj = ResourceManager.GetObject("News48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenImage {
            get {
                object obj = ResourceManager.GetObject("OpenImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PasteImage {
            get {
                object obj = ResourceManager.GetObject("PasteImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RefreshImage {
            get {
                object obj = ResourceManager.GetObject("RefreshImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
